apiVersion: v1
kind: Namespace
metadata:
  name: "test-namespace"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test-deployment"
  namespace: "test-namespace"
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:

        - name: wordpress
          image: quay.io/examples/go-http-headers
          ports:
            - containerPort: 8080
          args:
            - --port=8080
            - --name=wordpress

        - name: ftp
          image: quay.io/examples/go-http-headers
          ports:
            - containerPort: 8081
          args:
            - --port=8081
            - --name=ftp

        - name: phpmyadmin
          image: quay.io/examples/go-http-headers
          ports:
            - containerPort: 8082
          args:
            - --port=8082
            - --name=phpmyadmin

---
apiVersion: v1
kind: Service
metadata:
  name: "test-service"
  namespace: "test-namespace"
spec:
  ports:
    - name: wordpress
      port: 8080
      targetPort: 8080
    - name: ftp
      port: 8081
      targetPort: 8081
    - name: phpmyadmin
      port: 8082
      targetPort: 8082
  selector:
    app: app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "test-ingress"
  namespace: "test-namespace"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - example.example.com
      - ftp-example.example.com
      - phpmyadmin-example.example.com
  rules:
    - host: example.example.com
      http:
        paths:
          - backend:
              serviceName: "test-service"
              servicePort: 8080
    - host: ftp-example.example.com
      http:
        paths:
          - backend:
              serviceName: "test-service"
              servicePort: 8081

    - host: phpmyadmin-example.example.com
      http:
        paths:
          - backend:
              serviceName: "test-service"
              servicePort: 8082
